# src/phase5_text2sql/validator.py
#
# SQL security validation — the most critical safety layer in Phase 5.
#
# WHY THIS EXISTS:
# We give an LLM the ability to generate SQL that runs against a production
# database. Without strict validation, a prompt-injected query could:
#
#   Destructive: DROP TABLE pods; DELETE FROM audit_log WHERE 1=1;
#   Data dump:   SELECT * FROM audit_log;  -- exposes all user questions
#   Escalation:  SELECT pg_read_file('/etc/passwd');
#   Exfiltration:SELECT password FROM pg_authid;
#
# FOUR VALIDATION LAYERS (defense in depth):
#
# Layer 1: Statement type check
#   Parse the first keyword. Only SELECT is allowed.
#   Catches: INSERT, UPDATE, DELETE, DROP, CREATE, ALTER, TRUNCATE, EXEC
#
# Layer 2: Keyword blocklist
#   Scan the full SQL text for dangerous patterns regardless of position.
#   Catches: multi-statement attacks ("SELECT 1; DROP TABLE pods"),
#             function calls ("pg_read_file"), system catalogue access
#
# Layer 3: LIMIT requirement
#   Every query must include a LIMIT clause.
#   Catches: unbounded SELECT * FROM pods returning all rows
#
# Layer 4: System table access check
#   Block access to pg_catalog, information_schema, pg_roles, etc.
#   Catches: metadata enumeration, privilege escalation
#
# WHY NOT USE A SQL PARSER?
# sqlparse/sqlglot would give more precise parsing. We use regex + string
# matching for portability and simplicity. The combination of all four
# layers provides sufficient protection for our use case.
# Production systems should add sqlglot + allowlist of table names.

import re
from dataclasses import dataclass


@dataclass
class ValidationResult:
    is_valid: bool
    reason:   str = ""


# ── Dangerous keywords (any appearance = reject) ─────────────────────────────

BLOCKED_KEYWORDS = {
    # Data manipulation
    "INSERT", "UPDATE", "DELETE", "MERGE", "UPSERT",
    # Schema modification
    "DROP", "CREATE", "ALTER", "TRUNCATE", "RENAME",
    # Procedure execution
    "EXEC", "EXECUTE", "CALL",
    # Privilege changes
    "GRANT", "REVOKE",
    # PostgreSQL-specific dangerous functions
    "PG_READ_FILE", "PG_EXECUTE_SERVER_PROGRAM",
    "COPY",
    # Multi-statement separator
    ";",
}

# System tables that expose internal PostgreSQL data
BLOCKED_TABLE_PATTERNS = [
    r"\bpg_catalog\b",
    r"\binformation_schema\b",
    r"\bpg_authid\b",
    r"\bpg_shadow\b",
    r"\bpg_user\b",
    r"\bpg_roles\b",
    r"\bpg_stat_activity\b",
]

# Allowed tables in our operational schema
ALLOWED_TABLES = {
    "clusters", "pods", "nodes", "incidents",
    "deployments", "alerts", "audit_log",
}


def validate_sql(sql: str) -> ValidationResult:
    """
    Validate a SQL string against security rules.

    Called by sql_validate_node before the interrupt() HITL step.
    If validation fails, the query is REJECTED without human involvement.
    If validation passes, the human still gets to review before execution.

    Args:
        sql: The SQL string generated by the LLM

    Returns:
        ValidationResult(is_valid=True/False, reason="...")
    """
    if not sql or not sql.strip():
        return ValidationResult(False, "SQL query is empty")

    # Normalise whitespace for analysis
    sql_clean    = sql.strip()
    sql_upper    = sql_clean.upper()
    sql_no_space = re.sub(r'\s+', ' ', sql_upper)

    # ── Layer 1: Statement type ────────────────────────────────────────────
    # Extract the first non-comment, non-whitespace word
    first_word = re.search(r'\b(\w+)\b', sql_upper)
    if not first_word:
        return ValidationResult(False, "Cannot determine SQL statement type")

    first_keyword = first_word.group(1)
    if first_keyword != "SELECT":
        return ValidationResult(
            False,
            f"Only SELECT queries are allowed. Found: {first_keyword}. "
            "This system does not permit INSERT, UPDATE, DELETE, DROP, or other write operations."
        )

    # ── Layer 2: Keyword blocklist ─────────────────────────────────────────
    for keyword in BLOCKED_KEYWORDS:
        # Check as whole word (avoid false positives: "EXECUTE" vs "execute_id")
        pattern = r'\b' + re.escape(keyword) + r'\b' if keyword.isalpha() else re.escape(keyword)
        if re.search(pattern, sql_upper):
            return ValidationResult(
                False,
                f"Blocked keyword detected: '{keyword}'. "
                "Query rejected for security reasons."
            )

    # ── Layer 3: System table access ──────────────────────────────────────
    for pattern in BLOCKED_TABLE_PATTERNS:
        if re.search(pattern, sql_clean, re.IGNORECASE):
            return ValidationResult(
                False,
                f"Access to system tables is not permitted. "
                f"Only these tables are allowed: {', '.join(sorted(ALLOWED_TABLES))}"
            )

    # ── Layer 4: LIMIT requirement ────────────────────────────────────────
    if not re.search(r'\bLIMIT\b', sql_upper):
        return ValidationResult(
            False,
            "Query must include a LIMIT clause to prevent unbounded result sets. "
            "Maximum allowed: LIMIT 100"
        )

    # Extract LIMIT value and check it's reasonable
    limit_match = re.search(r'\bLIMIT\s+(\d+)', sql_upper)
    if limit_match:
        limit_value = int(limit_match.group(1))
        if limit_value > 100:
            return ValidationResult(
                False,
                f"LIMIT {limit_value} exceeds maximum allowed (100). "
                "Reduce the LIMIT clause to at most 100."
            )

    return ValidationResult(True, "Query passed all security checks")


def sanitize_for_display(sql: str) -> str:
    """
    Format SQL for human review display (indentation, line breaks).
    This is what the SRE sees in the HITL approval UI.
    """
    import sqlparse
    try:
        return sqlparse.format(
            sql,
            reindent=True,
            keyword_case='upper',
            identifier_case='lower',
        )
    except Exception:
        return sql  # return as-is if formatting fails
